# OtterTune Driver Configuration for On-Prem Deployment
# On-Prem customers need to specify correct driver option values in this config file

# ====================================================================
#  SERVER OPTIONS
# ====================================================================
# This section is required for connecting to the ottertune compute server

# URL of the OtterTune server that the driver communicates with
server_url: 'https://dev.api.ottertune.com'

# ====================================================================
#  METRICS OPTIONS
# ====================================================================
# This section is required for determining what metrics to collect

metric_source: ["cloudwatch"]

# ====================================================================
#  DRIVER OPTIONS
# ====================================================================
# Setup pertinent to ottertune agent driver behavior

monitor_interval: 60
